"""
Registry of live TV news streams.

All embed URLs point to YouTube Live streams. Video IDs may change when
broadcasters restart their streams; a periodic verification job can update
these. The IDs listed here are the long-running, well-known live stream
IDs for each channel as of early 2025.
"""

TV_CHANNELS: list[dict] = [
    # --- Middle East ---
    {
        "name": "Al Jazeera English",
        "embed_url": "https://www.youtube.com/embed/gCNeDWCI0vo?autoplay=1",
        "url": "https://www.youtube.com/watch?v=gCNeDWCI0vo",
        "region": "middle_east",
        "country": "Qatar",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/gCNeDWCI0vo/hqdefault.jpg",
    },
    {
        "name": "Al Jazeera Arabic",
        "embed_url": "https://www.youtube.com/embed/bNyUyrR0PHo?autoplay=1",
        "url": "https://www.youtube.com/watch?v=bNyUyrR0PHo",
        "region": "middle_east",
        "country": "Qatar",
        "language": "ar",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/bNyUyrR0PHo/hqdefault.jpg",
    },
    {
        "name": "TRT World",
        "embed_url": "https://www.youtube.com/embed/CV5Fooi8DIw?autoplay=1",
        "url": "https://www.youtube.com/watch?v=CV5Fooi8DIw",
        "region": "middle_east",
        "country": "Turkey",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/CV5Fooi8DIw/hqdefault.jpg",
    },
    {
        "name": "Al Arabiya",
        "embed_url": "https://www.youtube.com/embed/1Uw6ZkbsAH8?autoplay=1",
        "url": "https://www.youtube.com/watch?v=1Uw6ZkbsAH8",
        "region": "middle_east",
        "country": "UAE",
        "language": "ar",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/1Uw6ZkbsAH8/hqdefault.jpg",
    },
    {
        "name": "Iran International",
        "embed_url": "https://www.youtube.com/embed/FG0fTKAqZ5g?autoplay=1",
        "url": "https://www.youtube.com/watch?v=FG0fTKAqZ5g",
        "region": "middle_east",
        "country": "UK",
        "language": "fa",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/FG0fTKAqZ5g/hqdefault.jpg",
    },
    {
        "name": "i24NEWS English",
        "embed_url": "https://www.youtube.com/embed/cyG9sVGIXSs?autoplay=1",
        "url": "https://www.youtube.com/watch?v=cyG9sVGIXSs",
        "region": "middle_east",
        "country": "Israel",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/cyG9sVGIXSs/hqdefault.jpg",
    },
    # --- Europe ---
    {
        "name": "France 24 English",
        "embed_url": "https://www.youtube.com/embed/h3MuIUNCCzI?autoplay=1",
        "url": "https://www.youtube.com/watch?v=h3MuIUNCCzI",
        "region": "europe",
        "country": "France",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/h3MuIUNCCzI/hqdefault.jpg",
    },
    {
        "name": "France 24 French",
        "embed_url": "https://www.youtube.com/embed/l8PMl7tUDIE?autoplay=1",
        "url": "https://www.youtube.com/watch?v=l8PMl7tUDIE",
        "region": "europe",
        "country": "France",
        "language": "fr",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/l8PMl7tUDIE/hqdefault.jpg",
    },
    {
        "name": "DW News",
        "embed_url": "https://www.youtube.com/embed/GE_SfNVNyqk?autoplay=1",
        "url": "https://www.youtube.com/watch?v=GE_SfNVNyqk",
        "region": "europe",
        "country": "Germany",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/GE_SfNVNyqk/hqdefault.jpg",
    },
    {
        "name": "Sky News",
        "embed_url": "https://www.youtube.com/embed/9Auq9mYxFEE?autoplay=1",
        "url": "https://www.youtube.com/watch?v=9Auq9mYxFEE",
        "region": "europe",
        "country": "United Kingdom",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/9Auq9mYxFEE/hqdefault.jpg",
    },
    {
        "name": "Euronews English",
        "embed_url": "https://www.youtube.com/embed/pykpO5kQJ98?autoplay=1",
        "url": "https://www.youtube.com/watch?v=pykpO5kQJ98",
        "region": "europe",
        "country": "France",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/pykpO5kQJ98/hqdefault.jpg",
    },
    {
        "name": "BBC News (unofficial relay)",
        "embed_url": "https://www.youtube.com/embed/drJCxSsGMCo?autoplay=1",
        "url": "https://www.youtube.com/watch?v=drJCxSsGMCo",
        "region": "europe",
        "country": "United Kingdom",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/drJCxSsGMCo/hqdefault.jpg",
    },
    # --- Asia ---
    {
        "name": "NDTV 24x7",
        "embed_url": "https://www.youtube.com/embed/WB0HMj1cL64?autoplay=1",
        "url": "https://www.youtube.com/watch?v=WB0HMj1cL64",
        "region": "asia",
        "country": "India",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/WB0HMj1cL64/hqdefault.jpg",
    },
    {
        "name": "NHK World Japan",
        "embed_url": "https://www.youtube.com/embed/f0lYkdA-Gtc?autoplay=1",
        "url": "https://www.youtube.com/watch?v=f0lYkdA-Gtc",
        "region": "asia",
        "country": "Japan",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/f0lYkdA-Gtc/hqdefault.jpg",
    },
    {
        "name": "CGTN",
        "embed_url": "https://www.youtube.com/embed/LjBLSpVYtKg?autoplay=1",
        "url": "https://www.youtube.com/watch?v=LjBLSpVYtKg",
        "region": "asia",
        "country": "China",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/LjBLSpVYtKg/hqdefault.jpg",
    },
    {
        "name": "Arirang TV",
        "embed_url": "https://www.youtube.com/embed/S8Jl6p36akI?autoplay=1",
        "url": "https://www.youtube.com/watch?v=S8Jl6p36akI",
        "region": "asia",
        "country": "South Korea",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/S8Jl6p36akI/hqdefault.jpg",
    },
    {
        "name": "CNA 24/7",
        "embed_url": "https://www.youtube.com/embed/XWq5kBlakcQ?autoplay=1",
        "url": "https://www.youtube.com/watch?v=XWq5kBlakcQ",
        "region": "asia",
        "country": "Singapore",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/XWq5kBlakcQ/hqdefault.jpg",
    },
    # --- Americas ---
    {
        "name": "ABC News Live",
        "embed_url": "https://www.youtube.com/embed/w_Ma8oQLmSM?autoplay=1",
        "url": "https://www.youtube.com/watch?v=w_Ma8oQLmSM",
        "region": "americas",
        "country": "United States",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/w_Ma8oQLmSM/hqdefault.jpg",
    },
    {
        "name": "NBC News NOW",
        "embed_url": "https://www.youtube.com/embed/gXnHqpt3bZk?autoplay=1",
        "url": "https://www.youtube.com/watch?v=gXnHqpt3bZk",
        "region": "americas",
        "country": "United States",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/gXnHqpt3bZk/hqdefault.jpg",
    },
    {
        "name": "CBS News 24/7",
        "embed_url": "https://www.youtube.com/embed/plqZ_bMkDqs?autoplay=1",
        "url": "https://www.youtube.com/watch?v=plqZ_bMkDqs",
        "region": "americas",
        "country": "United States",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/plqZ_bMkDqs/hqdefault.jpg",
    },
    {
        "name": "LiveNOW from FOX",
        "embed_url": "https://www.youtube.com/embed/Z-ElhMFgRkk?autoplay=1",
        "url": "https://www.youtube.com/watch?v=Z-ElhMFgRkk",
        "region": "americas",
        "country": "United States",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/Z-ElhMFgRkk/hqdefault.jpg",
    },
    {
        "name": "CNN en Espanol",
        "embed_url": "https://www.youtube.com/embed/OhdrVBbAAiw?autoplay=1",
        "url": "https://www.youtube.com/watch?v=OhdrVBbAAiw",
        "region": "americas",
        "country": "United States",
        "language": "es",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/OhdrVBbAAiw/hqdefault.jpg",
    },
    # --- Africa ---
    {
        "name": "Africanews",
        "embed_url": "https://www.youtube.com/embed/NiRIbKwAejk?autoplay=1",
        "url": "https://www.youtube.com/watch?v=NiRIbKwAejk",
        "region": "africa",
        "country": "Republic of Congo",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/NiRIbKwAejk/hqdefault.jpg",
    },
    {
        "name": "SABC News",
        "embed_url": "https://www.youtube.com/embed/NfjFQPxoFBw?autoplay=1",
        "url": "https://www.youtube.com/watch?v=NfjFQPxoFBw",
        "region": "africa",
        "country": "South Africa",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/NfjFQPxoFBw/hqdefault.jpg",
    },
    {
        "name": "Channels TV Nigeria",
        "embed_url": "https://www.youtube.com/embed/Bv2fJb2f9Zg?autoplay=1",
        "url": "https://www.youtube.com/watch?v=Bv2fJb2f9Zg",
        "region": "africa",
        "country": "Nigeria",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/Bv2fJb2f9Zg/hqdefault.jpg",
    },
    {
        "name": "KTN News Kenya",
        "embed_url": "https://www.youtube.com/embed/TLjVBlu5qWo?autoplay=1",
        "url": "https://www.youtube.com/watch?v=TLjVBlu5qWo",
        "region": "africa",
        "country": "Kenya",
        "language": "en",
        "category": "news",
        "thumbnail_url": "https://img.youtube.com/vi/TLjVBlu5qWo/hqdefault.jpg",
    },
]


def get_tv_channels(
    region: str | None = None,
    language: str | None = None,
) -> list[dict]:
    """
    Return TV channels, optionally filtered by region and/or language.
    """
    channels = TV_CHANNELS
    if region:
        channels = [c for c in channels if c["region"] == region]
    if language:
        channels = [c for c in channels if c["language"] == language]
    return channels
